services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: FastAPI

    image: tumble-guard
    ports: 
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - db_data:/app/database
  
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env

  mqtt_worker:
    container_name: mqtt_worker
    build:
      context: .
      dockerfile: Dockerfile
    image: tumble-guard
    command: ["python", "/app/mqtt_worker.py"]
    env_file:
      - .env
    volumes:
      - db_data:/app/database
    depends_on:
      - web
      - tunnel

  broker:
    container_name: broker
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  db_data: