"""add mqtt alerts

Revision ID: 1491ab40c158
Revises: d5e6f7a8b9c0
Create Date: 2026-09-23 18:20:50.913685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1491ab40c158'
down_revision: Union[str, Sequence[str], None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # SQLite does not support ALTER TABLE ... ADD CONSTRAINT.  Batch mode
    # recreates the table and applies the constraint during the copy.
    with op.batch_alter_table('sensors') as batch_op:
        batch_op.add_column(sa.Column('mqtt_username', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('mqtt_column', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_state', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_sensors_mqtt_username', ['mqtt_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors') as batch_op:
        batch_op.drop_constraint('uq_sensors_mqtt_username', type_='unique')
        batch_op.drop_column('last_state')
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('mqtt_column')
        batch_op.drop_column('mqtt_username')
    op.drop_table('sensor_alerts')
    # ### end Alembic commands ###
